# Generated by Django 5.0.4 on 2024-05-11 00:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("VanPhongPham", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sanpham",
            name="MaSP",
        ),
    ]
