# Generated by Django 5.0.4 on 2024-05-11 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("VanPhongPham", "0004_alter_sanpham_dongia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DonHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("HoTen", models.CharField(max_length=100)),
                ("DiaChi", models.CharField(max_length=200)),
                ("Email", models.EmailField(max_length=254)),
                ("SDT", models.CharField(max_length=20)),
                ("PTTT", models.CharField(max_length=100)),
                ("SP", models.ManyToManyField(to="VanPhongPham.sanpham")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
