# Generated by Django 5.0.4 on 2024-05-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("VanPhongPham", "0005_donhang"),
    ]

    operations = [
        migrations.AddField(
            model_name="sanpham",
            name="SLBan",
            field=models.IntegerField(default=0),
        ),
    ]
