# Generated by Django 5.0.4 on 2024-05-13 01:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("VanPhongPham", "0006_sanpham_slban"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donhang",
            name="Email",
        ),
    ]
