# Generated by Django 5.0.4 on 2024-05-14 02:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("VanPhongPham", "0007_remove_donhang_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donhang",
            name="DiaChi",
        ),
        migrations.RemoveField(
            model_name="donhang",
            name="HoTen",
        ),
        migrations.RemoveField(
            model_name="donhang",
            name="PTTT",
        ),
        migrations.RemoveField(
            model_name="donhang",
            name="SDT",
        ),
        migrations.RemoveField(
            model_name="donhang",
            name="SP",
        ),
        migrations.RemoveField(
            model_name="giohang",
            name="ngay_tao",
        ),
        migrations.AddField(
            model_name="donhang",
            name="ngay_tao",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="giohang",
            name="so_luong",
            field=models.IntegerField(default="1"),
        ),
        migrations.CreateModel(
            name="ChiTietDonHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("so_luong", models.IntegerField()),
                (
                    "DonHang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="VanPhongPham.donhang",
                    ),
                ),
                ("SP", models.ManyToManyField(to="VanPhongPham.sanpham")),
            ],
        ),
        migrations.CreateModel(
            name="ThongTinNguoiNhan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("HoTen", models.CharField(max_length=100)),
                ("DiaChi", models.CharField(max_length=200)),
                ("SDT", models.CharField(max_length=20)),
                ("PTTT", models.CharField(max_length=100)),
                (
                    "DonHang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="VanPhongPham.donhang",
                    ),
                ),
            ],
        ),
    ]
