# Generated by Django 5.0.4 on 2024-05-14 02:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("VanPhongPham", "0008_remove_donhang_diachi_remove_donhang_hoten_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chitietdonhang",
            name="SP",
        ),
        migrations.AlterField(
            model_name="donhang",
            name="ngay_tao",
            field=models.DateTimeField(),
        ),
    ]
