# Generated by Django 5.0.4 on 2024-05-14 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "VanPhongPham",
            "0009_remove_chitietdonhang_sp_alter_donhang_ngay_tao_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="donhang",
            name="ngay_tao",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 14, 2, 34, 28, 126956, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
