# Generated by Django 5.0.4 on 2024-05-14 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("VanPhongPham", "0010_alter_donhang_ngay_tao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donhang",
            name="ngay_tao",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 14, 2, 37, 40, 262737, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
