# Generated by Django 5.0.4 on 2024-05-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("VanPhongPham", "0013_alter_donhang_ngay_tao"),
    ]

    operations = [
        migrations.AddField(
            model_name="chitietdonhang",
            name="san_pham",
            field=models.ManyToManyField(to="VanPhongPham.sanpham"),
        ),
    ]
