# Generated by Django 5.0.4 on 2024-05-14 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("VanPhongPham", "0014_chitietdonhang_san_pham"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chitietdonhang",
            name="san_pham",
        ),
        migrations.AddField(
            model_name="chitietdonhang",
            name="san_pham",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="VanPhongPham.sanpham",
            ),
        ),
    ]
