# Generated by Django 5.0.4 on 2024-05-15 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("VanPhongPham", "0015_remove_chitietdonhang_san_pham_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DanhGia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SoSao", models.IntegerField()),
                ("BinhLuan", models.TextField(max_length=500)),
                (
                    "DonHang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="VanPhongPham.donhang",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
