# Generated by Django 5.0.4 on 2024-05-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("VanPhongPham", "0019_alter_danhgia_danhgiasao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="danhgia",
            name="san_pham",
        ),
        migrations.AddField(
            model_name="sanpham",
            name="danhgia",
            field=models.ManyToManyField(
                related_name="sanphams", to="VanPhongPham.danhgia"
            ),
        ),
    ]
